#pragma kernel IFFTX
#define PI 3.14159265358979323846264338328

Texture2D<float4> SrcTexReal;
Texture2D<float4> SrcTexImag;

RWTexture2D<float4> DstTexReal;
RWTexture2D<float4> DstTexImag;

uint M;
uint N;

groupshared float4 blockReal[1024];
groupshared float4 blockImag[1024];

[numthreads(1024 / 2, 1, 1)]
void IFFTX(uint id : SV_DispatchThreadID, uint grid : SV_GroupID, uint gi : SV_GroupIndex)
{
    {
        uint2 srcIndex0 = uint2(gi * 2, grid);
        uint2 srcIndex1 = uint2(gi * 2 + 1, grid);
    
        blockReal[gi * 2] = SrcTexReal[srcIndex0];
        blockReal[gi * 2 + 1] = SrcTexReal[srcIndex1];
        blockImag[gi * 2] = SrcTexImag[srcIndex0];
        blockImag[gi * 2 + 1] = SrcTexImag[srcIndex1];
    
        for (int loopidx = 0; loopidx < (int) M; loopidx++)
        {
            int dleng = 1 << (M - loopidx - 1);
            uint t = gi % dleng;
            uint t0 = (gi / dleng) * dleng * 2 + t;
            uint t1 = t0 + dleng;
            GroupMemoryBarrierWithGroupSync();
            float4 r1 = blockReal[t1];
            float4 i1 = blockImag[t1];
            float4 r0 = blockReal[t0] - r1;
            float4 i0 = blockImag[t0] - i1;
            float rad = PI * t / dleng;
            float fsin = sin(rad);
            float fcos = cos(rad);
            blockReal[t0] += r1;
            blockImag[t0] += i1;
            blockReal[t1] = r0 * fcos - i0 * fsin;
            blockImag[t1] = r0 * fsin + i0 * fcos;
        }
    
        GroupMemoryBarrierWithGroupSync();
        float4 real0 = blockReal[reversebits(gi * 2) >> (32 - M)];
        float4 real1 = blockReal[reversebits(gi * 2 + 1) >> (32 - M)];
        float4 imag0 = blockImag[reversebits(gi * 2) >> (32 - M)];
        float4 imag1 = blockImag[reversebits(gi * 2 + 1) >> (32 - M)];
        real1 = -real1;
        imag1 = -imag1;
    
        int2 destIndex1 = int2(grid, ((gi * 2) + N / 2) % N);
        int2 destIndex2 = int2(grid, ((gi * 2 + 1) + N / 2) % N);
    
        DstTexReal[destIndex1] = real0 / N;
        DstTexReal[destIndex2] = real1 / N;
        DstTexImag[destIndex1] = imag0 / N;
        DstTexImag[destIndex2] = imag1 / N;
    }
    
    GroupMemoryBarrierWithGroupSync();
    
    {
        uint2 srcIndex0 = uint2(gi * 2, grid + N);
        uint2 srcIndex1 = uint2(gi * 2 + 1, grid + N);
    
        blockReal[gi * 2 + 0] = SrcTexReal[srcIndex0];
        blockReal[gi * 2 + 1] = SrcTexReal[srcIndex1];
        blockImag[gi * 2 + 0] = SrcTexImag[srcIndex0];
        blockImag[gi * 2 + 1] = SrcTexImag[srcIndex1];
    
        for (int loopidx = 0; loopidx < (int) M; loopidx++)
        {
            int dleng = 1 << (M - loopidx - 1);
            uint t = gi % dleng;
            uint t0 = (gi / dleng) * dleng * 2 + t;
            uint t1 = t0 + dleng;
            GroupMemoryBarrierWithGroupSync();
            float4 r1 = blockReal[t1];
            float4 i1 = blockImag[t1];
            float4 r0 = blockReal[t0] - r1;
            float4 i0 = blockImag[t0] - i1;
            float rad = PI * t / dleng;
            float fsin = sin(rad);
            float fcos = cos(rad);
            blockReal[t0] += r1;
            blockImag[t0] += i1;
            blockReal[t1] = r0 * fcos - i0 * fsin;
            blockImag[t1] = r0 * fsin + i0 * fcos;
        }
    
        GroupMemoryBarrierWithGroupSync();
        float4 real0 = blockReal[reversebits(gi * 2) >> (32 - M)];
        float4 real1 = blockReal[reversebits(gi * 2 + 1) >> (32 - M)];
        float4 imag0 = blockImag[reversebits(gi * 2) >> (32 - M)];
        float4 imag1 = blockImag[reversebits(gi * 2 + 1) >> (32 - M)];
        real1 = -real1;
        imag1 = -imag1;
    
        int2 destIndex1 = int2(grid, ((gi * 2) + N / 2) % N + N);
        int2 destIndex2 = int2(grid, ((gi * 2 + 1) + N / 2) % N + N);
    
        float phase1 = -PI * (float(destIndex1.x) / (float) N + float(destIndex1.y - N) / (float) N);
        float phase2 = -PI * (float(destIndex2.x) / (float) N + float(destIndex2.y - N) / (float) N);
        
        float4 res1 = DstTexReal[destIndex1 - int2(0, N)] * 1;
        float4 res2 = DstTexReal[destIndex2 - int2(0, N)] * 1;
        
        GroupMemoryBarrierWithGroupSync();
        
        DstTexReal[destIndex1] = (-(real0 / N * cos(phase1) - imag0 / N * sin(phase1)) + res1) / 1;
        DstTexReal[destIndex2] = (-(real1 / N * cos(phase2) - imag1 / N * sin(phase2)) + res2) / 1;
        DstTexImag[destIndex1] = imag0 / N * cos(phase1) + real0 / N * sin(phase1);
        DstTexImag[destIndex2] = imag1 / N * cos(phase2) + real1 / N * sin(phase2);
    }
}