// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> Imag;
RWTexture2D<float4> Real;

int M;
int N;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    
    float2 texcoord = (float2(id.xy) / float(N) * 2.0f - 1.0f);
    
    float factor = smoothstep(0.99f, 0.9f, length(texcoord)) * step(1.0f / float(N) * 1.0f, length(texcoord));
    
    Real[id.xy] = length(Real[id.xy] + Imag[id.xy]);
    
    Real[id.xy + uint2(0, N)] = length(Real[id.xy]).rrrr;
}
