
#pragma kernel BlurPass
#pragma kernel FirstPassFilter
#pragma kernel SecondPassFilter
#pragma kernel ThirdPassFilter

Texture2D<float> SourceTex;
RWTexture2D<float> ResultBlurTex;
RWTexture2D<float4> ResultInside;
RWTexture2D<float4> ResultOutside;
RWTexture2D<float> Result;

float maxInside;
float maxOutside;

float ApproximateEdgeDelta(float2 grad, float a)
{
    if (grad.x == 0.0f || grad.y == 0.0f)
    {
        return 0.5f - a;
    }
    
    grad = abs(normalize(grad));
    
    float gmax = max(grad.x, grad.y);
    float gmin = min(grad.x, grad.y);

    float a1 = 0.5f * gmin / gmax;
    if (a < a1)
    {
        return 0.5f * (gmax + gmin) - sqrt(2.0f * gmax * gmin * a);
    }
    if (a < (1.0f - a1))
    {
        return (0.5f - a) * gmax;
    }
    
    return -0.5f * (gmax + gmin) + sqrt(2.0f * gmax * gmin * (1.0f - a));
}

float InitializeDistance(float2 grad, float a)
{
    if (a <= 0.0f)
    {
        return 10000000.0f;
    }
    if (a < 1.0f)
    {
        return ApproximateEdgeDelta(grad, a);
    }
    else
    {
        return 0.0f;
    }
}

float4 UpdateDistanceInside(float4 p, int2 pos, int2 offset)
{
    float4 neighbor = ResultInside[pos + offset];
    int2 ndelta = int2(neighbor.xy);
    float4 closest = ResultInside[pos + offset - ndelta];
    
    if (closest.a == 0.0f)
    {
        return p;
    }
    
    float2 delta = neighbor.xy - float2(offset);
    float dist = length(delta) + ApproximateEdgeDelta(delta, closest.a);
    if (dist < p.z)
    {
        p.xy = delta;
        p.z = dist;
    }
    
    return p;
}

float4 UpdateDistanceOutside(float4 p, int2 pos, int2 offset)
{
    float4 neighbor = ResultOutside[pos + offset];
    int2 ndelta = int2(neighbor.xy);
    float4 closest = ResultOutside[pos + offset - ndelta];
    
    if (closest.a == 0.0f)
    {
        return p;
    }
    
    float2 delta = neighbor.xy - float2(offset);
    float dist = length(delta) + ApproximateEdgeDelta(delta, closest.a);
    if (dist < p.z)
    {
        p.xy = delta;
        p.z = dist;
    }
    
    return p;
}

[numthreads(1,1,1)]
void BlurPass(uint3 id : SV_DispatchThreadID)
{
    float p = 0.0f;
    for (int i = 0; i < 9; i++)
    {
        int x = i % 3 - 1;
        int y = i / 3 - 1;
        p += SourceTex[(int2)id.xy + int2(x, y)];
    }
    
    ResultBlurTex[id.xy] = SourceTex[id.xy];
}

[numthreads(1,1,1)]
void FirstPassFilter(uint3 id : SV_DispatchThreadID)
{
    float3x3 verticalFilter = float3x3(-1, -2, -1, 0, 0, 0, 1, 2, 1);
    float3x3 horizontalFilter = float3x3(1, 0, -1, 2, 0, -2, 1, 0, -1);
    
    float resultVert = 0.0f;
    float resultHorz = 0.0f;
    uint i = 0;
    
    for (i = 0; i < 9; i++)
    {
        int x = i % 3 - 1;
        int y = i / 3 - 1;
        resultVert += verticalFilter[y + 1][x + 1] * SourceTex[int2(x, y) + id.xy].r;
    }
    
    for (i = 0; i < 9; i++)
    {
        int x = i % 3 - 1;
        int y = i / 3 - 1;
        resultHorz += horizontalFilter[y + 1][x + 1] * SourceTex[int2(x, y) + id.xy].r;
    }
    
    float2 grad = float2(resultHorz, resultVert);
    float alpha = SourceTex[id.xy].r;
    
    ResultInside[id.xy] = float4(0.0f, 0.0f, InitializeDistance(-grad, 1.0f - alpha), 1.0f - alpha);
    ResultOutside[id.xy] = float4(0.0f, 0.0f, InitializeDistance(grad, alpha), alpha);

}


[numthreads(1, 1, 1)]
void SecondPassFilter(uint3 id : SV_DispatchThreadID)
{
    float4 p = 0.0f;
    
    {
        p = ResultInside[id.xy];
        if (p.z > 0.0f)
        {
            p = UpdateDistanceInside(p, id.xy, int2(-1, 0));
            p = UpdateDistanceInside(p, id.xy, int2(-1, -1));
            p = UpdateDistanceInside(p, id.xy, int2(0, -1));
            p = UpdateDistanceInside(p, id.xy, int2(1, -1));
            p = UpdateDistanceInside(p, id.xy, int2(1, 0));
            p = UpdateDistanceInside(p, id.xy, int2(1, 1));
            p = UpdateDistanceInside(p, id.xy, int2(0, 1));
            p = UpdateDistanceInside(p, id.xy, int2(-1, 1));
        }
        
        ResultInside[id.xy] = p;
    }
    
    
    {
        p = ResultOutside[id.xy];
        if (p.z > 0.0f)
        {
            p = UpdateDistanceOutside(p, id.xy, int2(-1, 0));
            p = UpdateDistanceOutside(p, id.xy, int2(-1, -1));
            p = UpdateDistanceOutside(p, id.xy, int2(0, -1));
            p = UpdateDistanceOutside(p, id.xy, int2(1, -1));
            p = UpdateDistanceOutside(p, id.xy, int2(1, 0));
            p = UpdateDistanceOutside(p, id.xy, int2(1, 1));
            p = UpdateDistanceOutside(p, id.xy, int2(0, 1));
            p = UpdateDistanceOutside(p, id.xy, int2(-1, 1));
        }
        
        ResultOutside[id.xy] = p;
    }
}


[numthreads(1, 1, 1)]
void ThirdPassFilter(uint3 id : SV_DispatchThreadID)
{
    float idist = ResultInside[id.xy].z;
    float odist = ResultOutside[id.xy].z;
    
    float dist = 0.5f + (clamp(idist / maxInside, 0.0f, 1.0f) - clamp(odist / maxOutside, 0.0f, 1.0f));

    
    Result[id.xy] = dist;
}