// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> Source;

RWTexture2D<float4> DstReal;
RWTexture2D<float4> DstImag;

float Defocus;
float Aberration;
float PhaseNoiseStrength;

static const int M = 10;
static const int N = 1 << M;

  
float noise(float2 uv)
{
    return dot(uv, normalize(float2(1000.0f, 2000.0f)));
}


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 uv = (float2(id.xy) - float2(N, N) * 0.5f) / (0.5f * float(N));
    
    float r = length(uv);
    
    float A = Source[id.xy].r;
    
    float phi = 0.0f;
    
    phi += Defocus * r * r;

    phi += Aberration * r * r * r * r;
    
    if (r > 0.3f)
    {
        phi += noise(uv) * PhaseNoiseStrength;

    }
    
    DstReal[id.xy] = A * cos(phi);
    DstImag[id.xy] = A * sin(phi);
}