// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Multiply

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> KernelTexReal;
Texture2D<float4> KernelTexImag;
Texture2D<float4> SceneTexReal;
Texture2D<float4> SceneTexImag;

RWTexture2D<float4> DstTexReal;
RWTexture2D<float4> DstTexImag;

static const int M = 10;
static const int N = 1 << M;

[numthreads(8,8,1)]
void Multiply (uint3 id : SV_DispatchThreadID)
{
    float2 texcoord = (float2(id.xy) / float(N) * 2.0f - 1.0f);
    
    {
        float4 kernelReal = KernelTexReal[id.xy];
        float4 kernelImag = KernelTexImag[id.xy];
        float4 sceneReal = SceneTexReal[id.xy];
        float4 sceneImag = SceneTexImag[id.xy];
    
        float4 resultReal = sceneReal * kernelReal - sceneImag * kernelImag;
        float4 resultImag = sceneReal * kernelImag + sceneImag * kernelReal;
    
        DstTexReal[id.xy] = resultReal;
        DstTexImag[id.xy] = resultImag;
    }
    
    {
        float4 kernelReal = KernelTexReal[id.xy + uint2(0, N)];
        float4 kernelImag = KernelTexImag[id.xy + uint2(0, N)];
        float4 sceneReal = SceneTexReal[id.xy + uint2(0, N)];
        float4 sceneImag = SceneTexImag[id.xy + uint2(0, N)];
    
        float4 resultReal = sceneReal * kernelReal - sceneImag * kernelImag;
        float4 resultImag = sceneReal * kernelImag + sceneImag * kernelReal;
    
        DstTexReal[id.xy + uint2(0, N)] = resultReal;
        DstTexImag[id.xy + uint2(0, N)] = resultImag;
    }
}